### ISSUE TITLE
"Metamask not detected" popup

### ISSUE THREAD

**Issue by coinop-logan** [gianlucaschoefer/gianlucaschoefer.github.com#1]
This popup has a couple of problems. First, it comes up when Metamask is installed but just not yet unlocked--so the message is possibly misleading. Second, when Metamask is unlocked later, the page doesn't realize it (you must manually restart).

Instead of a popup, have it output to the html somewhere, with a link to the Metamask plugin page on the Chrome addon store. It would also be nice if it performed the check on a timer, so if the user does unlock it the page updates on its own.

**Comment by coinop-logan** [comment]
@gianlucaschoefer

**Comment by gianlucaschoefer** [comment]
I'm unable to reproduce the first issue of the alert coming up, when metamask is installed but not unlocked. What alert do you get exactly?

**Comment by coinop-logan** [comment]
Well, now I can't duplicate it either. Weird. I am sure it was this alert, though:

https://github.com/gianlucaschoefer/gianlucaschoefer.github.com/blob/master/script/browse.js#L77

For now, just change it to a console.log and close the issue. I'll let you know if it comes up again.

**Comment by gianlucaschoefer** [comment]
it still makes sense to include a link in the page when someone lands on it without metamask

**Comment by gianlucaschoefer** [comment]
Included a warning in a h1 tag
