### ISSUE TITLE
Truncated *string update event logs

### ISSUE THREAD

**Issue by coinop-logan** [gianlucaschoefer/gianlucaschoefer.github.com#2]
Events for payerString / recipientString have truncated descriptions. See https://gianlucaschoefer.github.io/layout/interact.html?contractAddress=0x4c02d2ff312eaa8ef253e1f083567ea8ac38b5ec

**Comment by coinop-logan** [comment]
I only updated the recipient and payer strings each once. If you compare the complete string to the event displayed below, you can see that only the last 5 or 6 characters get displayed.

**Comment by gianlucaschoefer** [comment]
The building of the string from the raw hex data received by the etherscan api was only set to the last 64 bytes instead to all string bytes.
