### ISSUE TITLE
Change logging of Committed event

### ISSUE THREAD

**Issue by coinop-logan** [gianlucaschoefer/gianlucaschoefer.github.com#4]
"Contract state changed to Committed" -> "[address] has committed.", also align to the right, as this is a recipient-initiated action.

**Comment by gianlucaschoefer** [comment]
Could you check that this happened only on contracts, where payer and recipient were the same address? If yes, this is not an issue as 

1. This wouldn't happen if used normally.
2. It is technically correct that all actions come from the payer, as the events show what address performed the action, not what "role"
