### ISSUE TITLE
"Expended" color

### ISSUE THREAD

**Issue by coinop-logan** [gianlucaschoefer/gianlucaschoefer.github.com#7]
Right now the "expended" color is exactly the same as the html table border color; this loses a lot of visual structure in both browse and interact. A quick fix would be to just make that gray much lighter (this would also go better with our other colors, which themselves are rather light).

**Comment by gianlucaschoefer** [comment]
Used following color code: #9ca2a3

**Comment by gianlucaschoefer** [comment]
changes not live. reopening

**Comment by gianlucaschoefer** [comment]
should be fixed now.
